// Curated solar-system dataset.
// Physical facts sourced from NASA Science (science.nasa.gov) and NASA planetary
// fact sheets. Visual parameters (radius, distance, speeds) are artistic — the
// real solar system is far too vast and empty to render literally to scale.

export interface Layer {
  name: string
  color: string
  /** Fraction of the body radius this layer's OUTER edge reaches (0–1). */
  outerRadius: number
  description: string
}

export interface Ring {
  inner: number
  outer: number
  color: string
}

export interface Moon {
  name: string
  /** Visual radius in scene units. */
  radius: number
  /** Orbit radius from the planet's center, in scene units. */
  distance: number
  /** Revolution speed in radians/second (sign sets direction). */
  speed: number
  color: string
}

// Scale factor mapping real planet diameters (km) to scene units for the
// "true relative size" view. Chosen so Jupiter lands near its illustrative size.
export const REAL_SCALE_K = 3.2 / 139820

export interface Body {
  id: string
  name: string
  type: 'star' | 'planet'
  tagline: string
  overview: string

  // --- Scene / visual parameters (not to scale) ---
  radius: number
  /** Semi-major axis of the orbit, in scene units. */
  distance: number
  orbitSpeed: number
  /** Orbital eccentricity (0 = circle). Exaggerated a little for visibility. */
  eccentricity?: number
  /** Orbital inclination in degrees — tilts the orbit out of the flat plane. */
  inclination?: number
  /** Longitude of the ascending node in degrees — orients the tilt. */
  node?: number
  spinSpeed: number
  axialTilt: number
  color: string

  /** Real equatorial diameter in km — powers the true-scale view & comparisons. */
  diameterKm: number
  /** Mean distance from the Sun in AU (0 for the Sun). */
  distanceAu: number
  /** Mean longitude at the J2000 epoch, in degrees — for "today's positions". */
  meanLongitude?: number
  /** Orbital period in days — for "today's positions". */
  orbitalPeriodDays?: number
  moons?: Moon[]
  emissive?: boolean
  ring?: Ring

  // --- Real-world facts ---
  stats: {
    diameter: string
    mass: string
    gravity: string
    distanceFromSun: string
    dayLength: string
    yearLength: string
    moons: string
  }
  temperature: {
    mean: string
    range?: string
    note?: string
  }
  atmosphere: string
  composition: string
  layers: Layer[]
  funFacts: string[]
  sources: { label: string; url: string }[]
}

const NASA = (slug: string, label: string) => ({
  label,
  url: `https://science.nasa.gov/${slug}/`,
})

export const bodies: Body[] = [
  {
    id: 'sun',
    name: 'The Sun',
    type: 'star',
    tagline: 'The star at the heart of our solar system',
    overview:
      'The Sun is a 4.6-billion-year-old G-type main-sequence star — a nearly perfect sphere of hot plasma that holds 99.8% of all the mass in the solar system. Its gravity binds everything from the largest planets to the tiniest debris in orbit. Deep in its core, nuclear fusion converts hydrogen into helium, releasing the light and heat that make life on Earth possible.',
    radius: 7,
    distance: 0,
    orbitSpeed: 0,
    spinSpeed: 0.02,
    axialTilt: 7.25,
    color: '#ffb642',
    emissive: true,
    diameterKm: 1391000,
    distanceAu: 0,
    stats: {
      diameter: '1,391,000 km (≈109 Earths)',
      mass: '1.989 × 10³⁰ kg (333,000 Earths)',
      gravity: '274 m/s² (28× Earth)',
      distanceFromSun: '—',
      dayLength: '≈25–35 Earth days (rotates faster at equator)',
      yearLength: 'Orbits the galaxy every ≈230 million years',
      moons: '8 planets & countless smaller bodies orbit it',
    },
    temperature: {
      mean: 'Surface ≈ 5,500 °C',
      range: 'Core ≈ 15,000,000 °C',
      note: 'The corona is paradoxically hotter than the surface, reaching millions of degrees.',
    },
    atmosphere:
      'The Sun has no solid surface — it is a churning ball of plasma. Its outer atmosphere (the corona) constantly streams charged particles outward as the solar wind, which shapes comet tails and sparks auroras on the planets. Sunspots, solar flares, and coronal mass ejections drive "space weather" across the whole solar system.',
    composition:
      'About 73% hydrogen and 25% helium by mass, with trace amounts of oxygen, carbon, iron, and other elements. Energy is generated by hydrogen-to-helium fusion in the core.',
    layers: [
      { name: 'Core', color: '#fff6d6', outerRadius: 0.25, description: 'Where fusion occurs at ~15 million °C, powering the entire Sun.' },
      { name: 'Radiative zone', color: '#ffd75e', outerRadius: 0.7, description: 'Energy slowly diffuses outward as photons over thousands of years.' },
      { name: 'Convective zone', color: '#ff9d2f', outerRadius: 0.92, description: 'Hot plasma rises and sinks in giant churning cells.' },
      { name: 'Photosphere', color: '#ff6a00', outerRadius: 1.0, description: 'The visible "surface" that emits the sunlight we see.' },
    ],
    funFacts: [
      'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.',
      'The Sun is so large that roughly 1.3 million Earths could fit inside it.',
      'Every second, the Sun converts about 600 million tons of hydrogen into helium.',
      'It is a "middle-aged" star, roughly halfway through its ~10-billion-year lifetime.',
    ],
    sources: [NASA('sun', 'NASA — The Sun'), NASA('sun/facts', 'NASA — Sun Facts')],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'planet',
    tagline: 'The smallest planet and the closest to the Sun',
    overview:
      'Mercury is the smallest planet in our solar system and the nearest to the Sun. A year there flies by in just 88 Earth days, but a single day-night cycle lasts 176 Earth days. Despite the scorching daytime heat, Mercury is not the hottest planet — it has almost no atmosphere to trap warmth, so its dark side plunges to bitter cold.',
    radius: 0.85,
    distance: 14,
    orbitSpeed: 0.048,
    eccentricity: 0.2,
    inclination: 7,
    node: 48,
    diameterKm: 4879,
    distanceAu: 0.39,
    meanLongitude: 252.25,
    orbitalPeriodDays: 87.969,
    spinSpeed: 0.02,
    axialTilt: 0.034,
    color: '#8c8c94',
    stats: {
      diameter: '4,879 km',
      mass: '3.30 × 10²³ kg (0.055 Earths)',
      gravity: '3.7 m/s² (38% of Earth)',
      distanceFromSun: '57.9 million km (0.39 AU)',
      dayLength: '59 Earth days (one rotation)',
      yearLength: '88 Earth days',
      moons: 'None',
    },
    temperature: {
      mean: '167 °C',
      range: '−173 °C (night) to 427 °C (day)',
      note: 'One of the largest temperature swings of any planet.',
    },
    atmosphere:
      'Mercury has essentially no atmosphere — only a wispy "exosphere" of atoms blasted off its surface by the solar wind and micrometeorite impacts. With no air to hold heat or wind to move it, there is no weather in the everyday sense, just extreme heat and cold.',
    composition:
      'A rocky (terrestrial) planet with an unusually large iron core making up about 85% of its radius, wrapped in a thin silicate mantle and crust. Its huge metallic core gives Mercury a weak but real magnetic field.',
    layers: [
      { name: 'Iron core', color: '#c98a54', outerRadius: 0.83, description: 'A giant metallic core — proportionally the largest of any planet.' },
      { name: 'Mantle', color: '#8a8a92', outerRadius: 0.97, description: 'A thin rocky silicate layer surrounding the core.' },
      { name: 'Crust', color: '#5f5f66', outerRadius: 1.0, description: 'A heavily cratered surface, scarred over billions of years.' },
    ],
    funFacts: [
      'Mercury is shrinking — as its core cools, the whole planet contracts, wrinkling its crust into cliffs.',
      'It has ice! Permanently shadowed craters near its poles hold frozen water despite the Sun’s proximity.',
      'You would weigh about a third of your Earth weight standing on Mercury.',
      'It races around the Sun faster than any other planet — about 47 km per second.',
    ],
    sources: [NASA('mercury', 'NASA — Mercury'), NASA('mercury/facts', 'NASA — Mercury Facts')],
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'planet',
    tagline: 'Earth’s scorching, cloud-shrouded twin',
    overview:
      'Venus is the second planet from the Sun and Earth’s closest planetary neighbor. Similar in size and structure to Earth, it is radically different in character: a runaway greenhouse effect has turned it into the hottest planet in the solar system, with a crushing atmosphere and clouds of sulfuric acid. It spins backwards and so slowly that a Venusian day is longer than its year.',
    radius: 1.1,
    distance: 19,
    orbitSpeed: 0.035,
    eccentricity: 0.1,
    inclination: 4,
    node: 77,
    diameterKm: 12104,
    distanceAu: 0.72,
    meanLongitude: 181.98,
    orbitalPeriodDays: 224.701,
    spinSpeed: -0.005,
    axialTilt: 177.4,
    color: '#e6cca0',
    stats: {
      diameter: '12,104 km',
      mass: '4.87 × 10²⁴ kg (0.815 Earths)',
      gravity: '8.9 m/s² (91% of Earth)',
      distanceFromSun: '108.2 million km (0.72 AU)',
      dayLength: '243 Earth days (retrograde)',
      yearLength: '225 Earth days',
      moons: 'None',
    },
    temperature: {
      mean: '465 °C',
      note: 'Hot enough to melt lead — the hottest planet in the solar system.',
    },
    atmosphere:
      'A thick atmosphere of carbon dioxide traps heat in a runaway greenhouse effect, and the surface pressure is about 90 times Earth’s — like being 900 m underwater. Perpetual clouds of sulfuric acid race around the planet, and the upper winds "super-rotate," lapping the slow-spinning surface every four days.',
    composition:
      'A terrestrial planet much like Earth: an iron core, a rocky mantle, and a basaltic crust reshaped by extensive volcanism. Its surface is a bone-dry landscape of vast volcanic plains, mountains, and thousands of volcanoes.',
    layers: [
      { name: 'Iron core', color: '#d99a52', outerRadius: 0.5, description: 'A metallic core similar in size to Earth’s.' },
      { name: 'Mantle', color: '#b06a3a', outerRadius: 0.9, description: 'A hot rocky mantle that drives widespread volcanism.' },
      { name: 'Crust', color: '#7a4a2a', outerRadius: 1.0, description: 'A young volcanic surface of basaltic rock.' },
    ],
    funFacts: [
      'Venus spins backwards: on Venus the Sun rises in the west and sets in the east.',
      'A day on Venus (243 Earth days) is longer than its year (225 Earth days).',
      'It is the brightest natural object in our night sky after the Moon.',
      'Venus is sometimes called Earth’s twin because they are so close in size and mass.',
    ],
    sources: [NASA('venus', 'NASA — Venus'), NASA('venus/facts', 'NASA — Venus Facts')],
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'planet',
    tagline: 'Our home — the only known world with life',
    overview:
      'Earth is the third planet from the Sun and the only place we know of that teems with life. It is a water world: liquid oceans cover about 71% of its surface, held in place by a protective atmosphere and a temperature range that keeps water liquid. A global magnetic field shields the surface from harmful solar and cosmic radiation.',
    radius: 1.25,
    distance: 25,
    orbitSpeed: 0.029,
    eccentricity: 0.12,
    inclination: 2,
    node: 0,
    diameterKm: 12742,
    distanceAu: 1.0,
    meanLongitude: 100.46,
    orbitalPeriodDays: 365.256,
    moons: [{ name: 'Moon', radius: 0.34, distance: 2.4, speed: 0.5, color: '#cfcfcf' }],
    spinSpeed: 0.05,
    axialTilt: 23.44,
    color: '#4f7cff',
    stats: {
      diameter: '12,742 km',
      mass: '5.97 × 10²⁴ kg',
      gravity: '9.8 m/s²',
      distanceFromSun: '149.6 million km (1 AU)',
      dayLength: '24 hours',
      yearLength: '365.25 days',
      moons: '1 (the Moon)',
    },
    temperature: {
      mean: '15 °C',
      range: '−89 °C to 58 °C',
      note: 'The only known planet where water is stable as solid, liquid, and gas.',
    },
    atmosphere:
      'Earth’s atmosphere is 78% nitrogen and 21% oxygen, with the oxygen produced and maintained by life. This blanket of air drives our weather — clouds, rain, storms, and wind — and its ozone layer absorbs damaging ultraviolet light. The tilt of Earth’s axis gives us seasons as it orbits the Sun.',
    composition:
      'A terrestrial planet with a solid iron inner core, a liquid iron outer core that generates its magnetic field, a thick rocky mantle, and a thin crust broken into moving tectonic plates.',
    layers: [
      { name: 'Inner core', color: '#ffe08a', outerRadius: 0.19, description: 'Solid iron and nickel, hotter than the Sun’s surface yet solid under immense pressure.' },
      { name: 'Outer core', color: '#ff9a3c', outerRadius: 0.55, description: 'Liquid metal whose churning generates Earth’s magnetic field.' },
      { name: 'Mantle', color: '#b4532a', outerRadius: 0.99, description: 'Hot rock that slowly flows, driving plate tectonics and volcanoes.' },
      { name: 'Crust', color: '#2f6f57', outerRadius: 1.0, description: 'The thin, rocky surface of continents and ocean floors where we live.' },
    ],
    funFacts: [
      'Earth is not perfectly round — it bulges slightly at the equator because it spins.',
      'It is the only planet not named after a Greek or Roman god.',
      'Earth’s magnetic field protects us from the solar wind and creates the auroras.',
      'A day is slowly getting longer — the Moon’s pull adds a few milliseconds each century.',
    ],
    sources: [NASA('earth', 'NASA — Earth'), NASA('earth/facts', 'NASA — Earth Facts')],
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'planet',
    tagline: 'The rusty Red Planet',
    overview:
      'Mars is the fourth planet from the Sun — a cold, desert world whose iron-rich dust gives it a distinctive reddish color. It is the most explored planet besides Earth, with rovers and orbiters searching for signs that it was once warmer and wetter. Ancient riverbeds, lake basins, and polar ice caps hint at a very different Martian past.',
    radius: 0.95,
    distance: 31,
    orbitSpeed: 0.024,
    eccentricity: 0.16,
    inclination: 5,
    node: 49,
    diameterKm: 6779,
    distanceAu: 1.52,
    meanLongitude: 355.43,
    orbitalPeriodDays: 686.98,
    moons: [
      { name: 'Phobos', radius: 0.06, distance: 1.5, speed: 1.3, color: '#9a8c7a' },
      { name: 'Deimos', radius: 0.05, distance: 2.0, speed: 0.85, color: '#a89a86' },
    ],
    spinSpeed: 0.048,
    axialTilt: 25.19,
    color: '#c1440e',
    stats: {
      diameter: '6,779 km',
      mass: '6.42 × 10²³ kg (0.107 Earths)',
      gravity: '3.7 m/s² (38% of Earth)',
      distanceFromSun: '227.9 million km (1.52 AU)',
      dayLength: '24.6 hours',
      yearLength: '687 Earth days',
      moons: '2 (Phobos & Deimos)',
    },
    temperature: {
      mean: '−65 °C',
      range: '−125 °C to 20 °C',
    },
    atmosphere:
      'Mars has a thin atmosphere of mostly carbon dioxide — less than 1% the pressure of Earth’s. It still has weather: wispy clouds, morning fog, frost, and planet-wide dust storms that can rage for weeks and blot out the sky. Winds whip up towering dust devils across its plains.',
    composition:
      'A terrestrial planet with an iron-nickel-sulfur core, a rocky mantle, and a crust rich in iron oxide (rust) that gives Mars its red hue. It hosts Olympus Mons, the tallest volcano in the solar system, and Valles Marineris, a canyon system stretching thousands of kilometers.',
    layers: [
      { name: 'Core', color: '#d98a4a', outerRadius: 0.5, description: 'An iron-nickel-sulfur core, at least partly liquid.' },
      { name: 'Mantle', color: '#9c3a1e', outerRadius: 0.92, description: 'A rocky silicate mantle that once fed enormous volcanoes.' },
      { name: 'Crust', color: '#7a2d16', outerRadius: 1.0, description: 'A dusty, iron-oxide-rich surface — the "rust" that makes Mars red.' },
    ],
    funFacts: [
      'Olympus Mons is about three times the height of Mount Everest.',
      'Mars has seasons like Earth because its axis is tilted at a similar angle.',
      'Its two tiny moons, Phobos and Deimos, are probably captured asteroids.',
      'Sunsets on Mars appear blue — the opposite of the reddish sunsets on Earth.',
    ],
    sources: [NASA('mars', 'NASA — Mars'), NASA('mars/facts', 'NASA — Mars Facts')],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'planet',
    tagline: 'The giant king of the planets',
    overview:
      'Jupiter is the largest planet in the solar system — a gas giant so massive that all the other planets combined would fit inside it more than twice. It is a swirling world of colorful cloud bands and violent storms, most famously the Great Red Spot, a storm larger than Earth that has raged for centuries. Jupiter has dozens of moons, including four large "Galilean" worlds.',
    radius: 2.4,
    distance: 44,
    orbitSpeed: 0.013,
    eccentricity: 0.1,
    inclination: 2,
    node: 100,
    diameterKm: 139820,
    distanceAu: 5.2,
    meanLongitude: 34.35,
    orbitalPeriodDays: 4332.59,
    moons: [
      { name: 'Io', radius: 0.16, distance: 3.4, speed: 0.9, color: '#e6d24a' },
      { name: 'Europa', radius: 0.14, distance: 4.1, speed: 0.72, color: '#d9c9a8' },
      { name: 'Ganymede', radius: 0.2, distance: 4.9, speed: 0.55, color: '#9a8f7a' },
      { name: 'Callisto', radius: 0.18, distance: 5.8, speed: 0.42, color: '#6f6455' },
    ],
    spinSpeed: 0.11,
    axialTilt: 3.13,
    color: '#d8ca9d',
    stats: {
      diameter: '139,820 km (≈11 Earths)',
      mass: '1.90 × 10²⁷ kg (318 Earths)',
      gravity: '24.8 m/s² (2.5× Earth)',
      distanceFromSun: '778.5 million km (5.2 AU)',
      dayLength: '9.9 hours',
      yearLength: '11.9 Earth years',
      moons: '95 confirmed',
    },
    temperature: {
      mean: '−145 °C (cloud tops)',
      note: 'Jupiter radiates more heat than it receives from the Sun.',
    },
    atmosphere:
      'Jupiter’s atmosphere is a turbulent sea of hydrogen and helium organized into light "zones" and dark "belts" of racing clouds. Winds top 500 km/h, and enormous storms swirl for years — the Great Red Spot has persisted for at least 150 years. Lightning and powerful auroras crackle across the giant.',
    composition:
      'A gas giant with no solid surface. Hydrogen and helium make up nearly all of it; deep inside, crushing pressure squeezes hydrogen into an exotic liquid-metallic form that generates the strongest magnetic field of any planet. It may hold a diffuse rocky-icy core.',
    layers: [
      { name: 'Core', color: '#cbb48a', outerRadius: 0.2, description: 'A dense, possibly diffuse core of rock and ice under immense pressure.' },
      { name: 'Metallic hydrogen', color: '#9a7bd0', outerRadius: 0.8, description: 'Liquid metallic hydrogen that generates a colossal magnetic field.' },
      { name: 'Liquid hydrogen', color: '#d8ca9d', outerRadius: 0.95, description: 'A deep ocean of liquid hydrogen with no solid boundary.' },
      { name: 'Atmosphere', color: '#efe1b8', outerRadius: 1.0, description: 'Banded clouds of ammonia and hydrogen racing at hundreds of km/h.' },
    ],
    funFacts: [
      'Jupiter has the shortest day of any planet, spinning once in under 10 hours.',
      'The Great Red Spot is a storm wide enough to swallow the entire Earth.',
      'Its moon Ganymede is the largest moon in the solar system — bigger than Mercury.',
      'Jupiter’s immense gravity helps shield the inner planets from comets and asteroids.',
    ],
    sources: [NASA('jupiter', 'NASA — Jupiter'), NASA('jupiter/facts', 'NASA — Jupiter Facts')],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'planet',
    tagline: 'The jewel of the solar system',
    overview:
      'Saturn is the sixth planet from the Sun and the second largest — a gas giant famous for its magnificent rings. Those rings are made of countless chunks of ice and rock, ranging from tiny grains to house-sized boulders, spread into a dazzling disc. Saturn is the least dense planet; it would float in a big enough bath of water.',
    radius: 2.0,
    distance: 58,
    orbitSpeed: 0.0096,
    eccentricity: 0.12,
    inclination: 4,
    node: 114,
    diameterKm: 116460,
    distanceAu: 9.54,
    meanLongitude: 49.94,
    orbitalPeriodDays: 10759.22,
    moons: [
      { name: 'Enceladus', radius: 0.07, distance: 4.8, speed: 0.7, color: '#f2f2f2' },
      { name: 'Rhea', radius: 0.1, distance: 5.2, speed: 0.58, color: '#b8b0a0' },
      { name: 'Titan', radius: 0.2, distance: 6.0, speed: 0.46, color: '#d89a4a' },
      { name: 'Iapetus', radius: 0.1, distance: 7.1, speed: 0.34, color: '#8a7a5a' },
    ],
    spinSpeed: 0.1,
    axialTilt: 26.73,
    color: '#e3d6a8',
    ring: { inner: 2.6, outer: 4.4, color: '#d9c9a0' },
    stats: {
      diameter: '116,460 km (≈9 Earths)',
      mass: '5.68 × 10²⁶ kg (95 Earths)',
      gravity: '10.4 m/s² (1.06× Earth)',
      distanceFromSun: '1.43 billion km (9.5 AU)',
      dayLength: '10.7 hours',
      yearLength: '29.4 Earth years',
      moons: '146 confirmed',
    },
    temperature: {
      mean: '−178 °C (cloud tops)',
    },
    atmosphere:
      'Like Jupiter, Saturn is a windy world of hydrogen and helium clouds arranged in faint bands. Its winds are among the fastest in the solar system, reaching 1,800 km/h near the equator. A bizarre, long-lived hexagon-shaped jet stream swirls around its north pole.',
    composition:
      'A gas giant of hydrogen and helium wrapped around a dense core of rock and ice. Deep inside, hydrogen becomes liquid and then metallic. Its glorious rings are almost entirely water ice, kept sharp and bright by the gravity of small "shepherd" moons.',
    layers: [
      { name: 'Core', color: '#cbb48a', outerRadius: 0.25, description: 'A dense core of rock and ice, several times Earth’s mass.' },
      { name: 'Metallic hydrogen', color: '#9a7bd0', outerRadius: 0.6, description: 'Liquid metallic hydrogen surrounding the core.' },
      { name: 'Liquid hydrogen', color: '#e3d6a8', outerRadius: 0.95, description: 'A vast layer of liquid hydrogen and helium.' },
      { name: 'Atmosphere', color: '#efe6c2', outerRadius: 1.0, description: 'Pale golden clouds streaked by the fastest winds of any ringed world.' },
    ],
    funFacts: [
      'Saturn is the only planet less dense than water — in theory, it would float.',
      'Its rings stretch about 280,000 km wide but are often only ~10 meters thick.',
      'A strange six-sided jet stream — the "hexagon" — circles its north pole.',
      'Saturn’s moon Titan has lakes and rivers of liquid methane and a thick atmosphere.',
    ],
    sources: [NASA('saturn', 'NASA — Saturn'), NASA('saturn/facts', 'NASA — Saturn Facts')],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'planet',
    tagline: 'The ice giant that rolls on its side',
    overview:
      'Uranus is the seventh planet from the Sun and the first found with a telescope. It is an "ice giant," made largely of icy fluids surrounding a small rocky core, which gives it a pale blue-green color. Its most unusual feature is its extreme tilt: Uranus is knocked over on its side, so it essentially rolls around the Sun like a barrel, giving it decades-long seasons.',
    radius: 1.3,
    distance: 70,
    orbitSpeed: 0.0068,
    eccentricity: 0.1,
    inclination: 3,
    node: 74,
    diameterKm: 50724,
    distanceAu: 19.19,
    meanLongitude: 313.23,
    orbitalPeriodDays: 30688.5,
    moons: [
      { name: 'Miranda', radius: 0.06, distance: 2.4, speed: 0.7, color: '#b6c5c8' },
      { name: 'Titania', radius: 0.11, distance: 2.9, speed: 0.52, color: '#c2ced0' },
      { name: 'Oberon', radius: 0.1, distance: 3.4, speed: 0.42, color: '#a7b0b2' },
    ],
    spinSpeed: -0.06,
    axialTilt: 97.77,
    color: '#9fe3e8',
    ring: { inner: 1.7, outer: 2.2, color: '#7f97a0' },
    stats: {
      diameter: '50,724 km (≈4 Earths)',
      mass: '8.68 × 10²⁵ kg (14.5 Earths)',
      gravity: '8.7 m/s² (89% of Earth)',
      distanceFromSun: '2.87 billion km (19.2 AU)',
      dayLength: '17.2 hours (retrograde)',
      yearLength: '84 Earth years',
      moons: '28 confirmed',
    },
    temperature: {
      mean: '−224 °C',
      note: 'The coldest planetary atmosphere in the solar system.',
    },
    atmosphere:
      'Uranus’s atmosphere is hydrogen and helium with a dash of methane, which absorbs red light and leaves the planet looking serenely blue-green. Though calm-looking, it hides winds up to 900 km/h and faint bands of clouds. Its sideways tilt drives extreme seasons — each pole spends about 42 years in sunlight, then 42 years in darkness.',
    composition:
      'An ice giant: a small rocky core surrounded by a dense, hot "icy" mantle of water, ammonia, and methane fluids, wrapped in a hydrogen-helium atmosphere. It also has a set of thin, dark rings and a strangely tilted, off-center magnetic field.',
    layers: [
      { name: 'Rocky core', color: '#9a8a6a', outerRadius: 0.3, description: 'A small core of rock and iron at the center.' },
      { name: 'Icy mantle', color: '#4fb9c4', outerRadius: 0.8, description: 'A hot, dense fluid of water, ammonia, and methane "ices".' },
      { name: 'Atmosphere', color: '#b6ecef', outerRadius: 1.0, description: 'Hydrogen, helium, and methane — the methane paints it blue-green.' },
    ],
    funFacts: [
      'Uranus rotates on its side, likely knocked over by a colossal ancient collision.',
      'It was the first planet discovered with a telescope, by William Herschel in 1781.',
      'Its seasons last about 21 years each because of its extreme tilt.',
      'Uranus and Neptune may rain diamonds deep in their interiors.',
    ],
    sources: [NASA('uranus', 'NASA — Uranus'), NASA('uranus/facts', 'NASA — Uranus Facts')],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'planet',
    tagline: 'The windiest world, far out in the dark',
    overview:
      'Neptune is the eighth and most distant planet from the Sun — a dark, cold ice giant whipped by supersonic winds. It is so far away that it was the first planet located by mathematical prediction rather than observation. A deep azure color and faint, clumpy rings make it one of the most striking worlds, though it is invisible to the naked eye.',
    radius: 1.25,
    distance: 80,
    orbitSpeed: 0.0054,
    eccentricity: 0.09,
    inclination: 3,
    node: 131,
    diameterKm: 49244,
    distanceAu: 30.07,
    meanLongitude: 304.88,
    orbitalPeriodDays: 60182,
    moons: [{ name: 'Triton', radius: 0.14, distance: 2.7, speed: -0.5, color: '#cdd6d0' }],
    spinSpeed: 0.06,
    axialTilt: 28.32,
    color: '#3b5bdb',
    stats: {
      diameter: '49,244 km (≈3.9 Earths)',
      mass: '1.02 × 10²⁶ kg (17 Earths)',
      gravity: '11.2 m/s² (1.14× Earth)',
      distanceFromSun: '4.5 billion km (30.1 AU)',
      dayLength: '16 hours',
      yearLength: '165 Earth years',
      moons: '16 confirmed',
    },
    temperature: {
      mean: '−214 °C',
      note: 'Radiates more heat than it receives, driving its ferocious winds.',
    },
    atmosphere:
      'Neptune’s atmosphere of hydrogen, helium, and methane hosts the fastest winds in the solar system — over 2,000 km/h. Great dark storms the size of Earth appear and vanish over years. As on Uranus, methane gives it a blue tint, but Neptune’s is a deeper, more vivid blue for reasons still not fully understood.',
    composition:
      'An ice giant much like Uranus: a rocky core inside a hot mantle of water, ammonia, and methane ices, beneath a hydrogen-helium atmosphere. It has a set of faint rings and 16 known moons, the largest being Triton, which orbits backwards.',
    layers: [
      { name: 'Rocky core', color: '#7a6a5a', outerRadius: 0.3, description: 'A dense core of rock and metal, roughly Earth’s mass.' },
      { name: 'Icy mantle', color: '#3f6fd0', outerRadius: 0.8, description: 'A hot fluid of water, ammonia, and methane — the bulk of the planet.' },
      { name: 'Atmosphere', color: '#4a6ff0', outerRadius: 1.0, description: 'Hydrogen, helium, and methane whipped by supersonic winds.' },
    ],
    funFacts: [
      'Neptune has the fastest winds in the solar system — faster than the speed of sound on Earth.',
      'It was discovered in 1846 using math, after astronomers predicted where it should be.',
      'Neptune has completed only one full orbit of the Sun since its discovery (in 2011).',
      'Its moon Triton orbits backwards and may be a captured dwarf planet.',
    ],
    sources: [NASA('neptune', 'NASA — Neptune'), NASA('neptune/facts', 'NASA — Neptune Facts')],
  },
]

export const bodyById = (id: string): Body | undefined => bodies.find((b) => b.id === id)

// Approximate heliocentric mean longitude (degrees) for a planet right now,
// propagated from its J2000 mean longitude by its orbital period. Good enough
// to reproduce today's rough planetary alignment.
const J2000 = Date.UTC(2000, 0, 1, 12, 0, 0)
export const currentMeanLongitude = (body: Body): number | null => {
  if (body.meanLongitude == null || body.orbitalPeriodDays == null) return null
  const days = (Date.now() - J2000) / 86_400_000
  return body.meanLongitude + 360 * (days / body.orbitalPeriodDays)
}
